- hosts: Datanode , Namenode

  tasks:
   - name: "Copying Hadoop & JDK in Namenode and Datanode"
     copy:
          src: "{{ item }}"
          dest: "/root/"
     loop:
         - "./hadoop-1.2.1-1.x86_64.rpm"
         - "./jdk-8u171-linux-x64.rpm"

   - name: "Installing JDK and Hadoop"
     shell: "rpm -i /root/jdk-8u171-linux-x64.rpm --force && rpm -i /root/hadoop-1.2.1-1.x86_64.rpm --force"

   - name: "Disabling Firewall"
     service:
         name: "firewalld"
         state: stopped

   - name: "Setting SELinux to Permissive Mode"
     selinux:
        policy: targeted
        state: permissive
